name: Build and Push Archon Docker Images
on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:
jobs:
  name: Build and Push Archon Docker Images
on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./original_archon/Dockerfile
          push: true
          tags: |
            normanjames/archon:backend-latest
      - name: Build and push UI Image
        uses: docker/build-push-action@v5
        with:
          context: ./archon-ui-main
          file: ./archon-ui-main/Dockerfile
          push: true
          tags: |
            normanjames/archon:ui-latestbuild-and-push:
